export const ALL_COUNTRIES = [
  { code: 'US', zh: '美国', en: 'United States' }, { code: 'HK', zh: '香港', en: 'Hong Kong' }, { code: 'JP', zh: '日本', en: 'Japan' }, { code: 'SG', zh: '新加坡', en: 'Singapore' }, { code: 'GB', zh: '英国', en: 'United Kingdom' }, { code: 'TW', zh: '台湾', en: 'Taiwan' }, { code: 'KR', zh: '韩国', en: 'South Korea' }, { code: 'DE', zh: '德国', en: 'Germany' }, { code: 'FR', zh: '法国', en: 'France' }, { code: 'AU', zh: '澳大利亚', en: 'Australia' },
  { code: 'CA', zh: '加拿大', en: 'Canada' }, { code: 'NL', zh: '荷兰', en: 'Netherlands' }, { code: 'IN', zh: '印度', en: 'India' }, { code: 'BR', zh: '巴西', en: 'Brazil' }, { code: 'RU', zh: '俄罗斯', en: 'Russia' }, { code: 'TR', zh: '土耳其', en: 'Turkey' }, { code: 'IT', zh: '意大利', en: 'Italy' }, { code: 'ES', zh: '西班牙', en: 'Spain' }, { code: 'CH', zh: '瑞士', en: 'Switzerland' }, { code: 'SE', zh: '瑞典', en: 'Sweden' },
  { code: 'PL', zh: '波兰', en: 'Poland' }, { code: 'CZ', zh: '捷克', en: 'Czech Republic' }, { code: 'FI', zh: '芬兰', en: 'Finland' }, { code: 'NO', zh: '挪威', en: 'Norway' }, { code: 'DK', zh: '丹麦', en: 'Denmark' }, { code: 'AR', zh: '阿根廷', en: 'Argentina' }, { code: 'MX', zh: '墨西哥', en: 'Mexico' }, { code: 'TH', zh: '泰国', en: 'Thailand' }, { code: 'ID', zh: '印度尼西亚', en: 'Indonesia' }, { code: 'VN', zh: '越南', en: 'Vietnam' },
  { code: 'PH', zh: '菲律宾', en: 'Philippines' }, { code: 'MY', zh: '马来西亚', en: 'Malaysia' }, { code: 'UA', zh: '乌克兰', en: 'Ukraine' }, { code: 'RO', zh: '罗马尼亚', en: 'Romania' }, { code: 'HU', zh: '匈牙利', en: 'Hungary' }, { code: 'BG', zh: '保加利亚', en: 'Bulgaria' }, { code: 'PT', zh: '葡萄牙', en: 'Portugal' }, { code: 'BE', zh: '比利时', en: 'Belgium' }, { code: 'AT', zh: '奥地利', en: 'Austria' }, { code: 'NZ', zh: '新西兰', en: 'New Zealand' },
  { code: 'IL', zh: '以色列', en: 'Israel' }, { code: 'ZA', zh: '南非', en: 'South Africa' }, { code: 'EG', zh: '埃及', en: 'Egypt' }, { code: 'AE', zh: '阿联酋', en: 'United Arab Emirates' }, { code: 'SA', zh: '沙特阿拉伯', en: 'Saudi Arabia' }, { code: 'IE', zh: '爱尔兰', en: 'Ireland' }, { code: 'GR', zh: '希腊', en: 'Greece' }, { code: 'CL', zh: '智利', en: 'Chile' }, { code: 'CO', zh: '哥伦比亚', en: 'Colombia' }, { code: 'PE', zh: '秘鲁', en: 'Peru' },
  { code: 'PK', zh: '巴基斯坦', en: 'Pakistan' }, { code: 'BD', zh: '孟加拉国', en: 'Bangladesh' }, { code: 'NG', zh: '尼日利亚', en: 'Nigeria' }, { code: 'KE', zh: '肯尼亚', en: 'Kenya' }, { code: 'MA', zh: '摩洛哥', en: 'Morocco' }, { code: 'DZ', zh: '阿尔及利亚', en: 'Algeria' }, { code: 'KZ', zh: '哈萨克斯坦', en: 'Kazakhstan' }, { code: 'UZ', zh: '乌兹别克斯坦', en: 'Uzbekistan' }, { code: 'LK', zh: '斯里兰卡', en: 'Sri Lanka' }, { code: 'NP', zh: '尼泊尔', en: 'Nepal' },
  { code: 'MM', zh: '缅甸', en: 'Myanmar' }, { code: 'KH', zh: '柬埔寨', en: 'Cambodia' }, { code: 'LA', zh: '老挝', en: 'Laos' }, { code: 'MN', zh: '蒙古', en: 'Mongolia' }, { code: 'KP', zh: '朝鲜', en: 'North Korea' }, { code: 'AF', zh: '阿富汗', en: 'Afghanistan' }, { code: 'IR', zh: '伊朗', en: 'Iran' }, { code: 'IQ', zh: '伊拉克', en: 'Iraq' }, { code: 'SY', zh: '叙利亚', en: 'Syria' }, { code: 'LB', zh: '黎巴嫩', en: 'Lebanon' },
  { code: 'JO', zh: '约旦', en: 'Jordan' }, { code: 'QA', zh: '卡塔尔', en: 'Qatar' }, { code: 'KW', zh: '科威特', en: 'Kuwait' }, { code: 'OM', zh: '阿曼', en: 'Oman' }, { code: 'BH', zh: '巴林', en: 'Bahrain' }, { code: 'CY', zh: '塞浦路斯', en: 'Cyprus' }, { code: 'MT', zh: '马耳他', en: 'Malta' }, { code: 'IS', zh: '冰岛', en: 'Iceland' }, { code: 'LU', zh: '卢森堡', en: 'Luxembourg' }, { code: 'MC', zh: '摩纳哥', en: 'Monaco' },
  { code: 'LI', zh: '列支敦士登', en: 'Liechtenstein' }, { code: 'SM', zh: '圣马力诺', en: 'San Marino' }, { code: 'AD', zh: '安道尔', en: 'Andorra' }, { code: 'EE', zh: '爱沙尼亚', en: 'Estonia' }, { code: 'LV', zh: '拉脱维亚', en: 'Latvia' }, { code: 'LT', zh: '立陶宛', en: 'Lithuania' }, { code: 'BY', zh: '白俄罗斯', en: 'Belarus' }, { code: 'MD', zh: '摩尔多瓦', en: 'Moldova' }, { code: 'GE', zh: '格鲁吉亚', en: 'Georgia' }, { code: 'AM', zh: '亚美尼亚', en: 'Armenia' },
  { code: 'AZ', zh: '阿塞拜疆', en: 'Azerbaijan' }, { code: 'RS', zh: '塞尔维亚', en: 'Serbia' }, { code: 'HR', zh: '克罗地亚', en: 'Croatia' }, { code: 'BA', zh: '波黑', en: 'Bosnia and Herzegovina' }, { code: 'ME', zh: '黑山', en: 'Montenegro' }, { code: 'MK', zh: '北马其顿', en: 'North Macedonia' }, { code: 'AL', zh: '阿尔巴尼亚', en: 'Albania' }, { code: 'SK', zh: '斯洛伐克', en: 'Slovakia' }, { code: 'SI', zh: '斯洛文尼亚', en: 'Slovenia' }, { code: 'EC', zh: '厄瓜多尔', en: 'Ecuador' },
  { code: 'VE', zh: '委内瑞拉', en: 'Venezuela' }, { code: 'UY', zh: '乌拉圭', en: 'Uruguay' }, { code: 'PY', zh: '巴拉圭', en: 'Paraguay' }, { code: 'BO', zh: '玻利维亚', en: 'Bolivia' }, { code: 'CU', zh: '古巴', en: 'Cuba' }, { code: 'JM', zh: '牙买加', en: 'Jamaica' }, { code: 'CR', zh: '哥斯达黎加', en: 'Costa Rica' }, { code: 'PA', zh: '巴拿马', en: 'Panama' }, { code: 'DO', zh: '多米尼加', en: 'Dominican Republic' }, { code: 'GT', zh: '危地马拉', en: 'Guatemala' },
  { code: 'HN', zh: '洪都拉斯', en: 'Honduras' }, { code: 'SV', zh: '萨尔瓦多', en: 'El Salvador' }, { code: 'NI', zh: '尼加拉瓜', en: 'Nicaragua' }, { code: 'PR', zh: '波多黎各', en: 'Puerto Rico' }, { code: 'BS', zh: '巴哈马', en: 'Bahamas' }, { code: 'TT', zh: '特立尼达和多巴哥', en: 'Trinidad and Tobago' }, { code: 'GH', zh: '加纳', en: 'Ghana' }, { code: 'CI', zh: '科特迪瓦', en: 'Ivory Coast' }, { code: 'SN', zh: '塞内加尔', en: 'Senegal' }, { code: 'CM', zh: '喀麦隆', en: 'Cameroon' },
  { code: 'AO', zh: '安哥拉', en: 'Angola' }, { code: 'MZ', zh: '莫桑比克', en: 'Mozambique' }, { code: 'ZM', zh: '赞比亚', en: 'Zambia' }, { code: 'ZW', zh: '津巴布韦', en: 'Zimbabwe' }, { code: 'UG', zh: '乌干达', en: 'Uganda' }, { code: 'TZ', zh: '坦桑尼亚', en: 'Tanzania' }, { code: 'ET', zh: '埃塞俄比亚', en: 'Ethiopia' }, { code: 'SD', zh: '苏丹', en: 'Sudan' }, { code: 'SS', zh: '南苏丹', en: 'South Sudan' }, { code: 'SO', zh: '索马里', en: 'Somalia' },
  { code: 'MG', zh: '马达加斯加', en: 'Madagascar' }, { code: 'MU', zh: '毛里求斯', en: 'Mauritius' }, { code: 'SC', zh: '塞舌尔', en: 'Seychelles' }, { code: 'MV', zh: '马尔代夫', en: 'Maldives' }, { code: 'FJ', zh: '斐济', en: 'Fiji' }, { code: 'PG', zh: '巴布亚新几内亚', en: 'Papua New Guinea' }
];
